#include <stdio.h>
#include <stdlib.h>


#define LEFT -1
#define RIGHT 1


void print_permutation(int *arr, int n) {
    for (int i = 0; i < n; i++)
        printf("%d ", arr[i]);
    printf("\n");
}


int get_largest_mobile(int *arr, int *dir, int n) {
    int largest_mobile_index = -1;
    int largest_mobile = 0;

    for (int i = 0; i < n; i++) {
        int neighbor_index = i + dir[i];
        if (neighbor_index >= 0 && neighbor_index < n) {
            if (arr[i] > arr[neighbor_index] && arr[i] > largest_mobile) {
                largest_mobile = arr[i];
                largest_mobile_index = i;
            }
        }
    }
    return largest_mobile_index;
}

void johnson_trotter(int n) {
    int *arr = malloc(n * sizeof(int));
    int *dir = malloc(n * sizeof(int));  

   
    for (int i = 0; i < n; i++) {
        arr[i] = i + 1;
        dir[i] = LEFT;
    }

    print_permutation(arr, n);

    while (1) {
        int largest_mobile_index = get_largest_mobile(arr, dir, n);
        if (largest_mobile_index == -1) break;  

        int swap_index = largest_mobile_index + dir[largest_mobile_index];

        int temp = arr[largest_mobile_index];
        arr[largest_mobile_index] = arr[swap_index];
        arr[swap_index] = temp;

        int temp_dir = dir[largest_mobile_index];
        dir[largest_mobile_index] = dir[swap_index];
        dir[swap_index] = temp_dir;

        largest_mobile_index = swap_index;

       
        for (int i = 0; i < n; i++) {
            if (arr[i] > arr[largest_mobile_index]) {
                dir[i] = -dir[i];
            }
        }

        print_permutation(arr, n);
    }

    free(arr);
    free(dir);
}

int main() {
    int n;
    printf("Enter number of elements: ");
    scanf("%d", &n);
    printf("All permutations generated by Johnson-Trotter algorithm:\n");
    johnson_trotter(n);
    return 0;
}
